import { useEffect, useState } from 'react';
import { api } from '../auth';
import { EmptyState, ErrorState, Page } from '../components/Page';
import { formatMoney } from '../utils/format';

export function GoldExchangeReportPage() {
  const [data,setData]=useState<any>(),[error,setError]=useState(''),[selected,setSelected]=useState<any>();
  async function load(){setError('');try{setData((await api.get('/pos/exchanges/report',{params:{page:1,page_size:100}})).data)}catch(reason:any){setError(reason.response?.data?.error?.message||'Unable to load Gold Exchange history.')}}
  useEffect(()=>{void load()},[]);
  return <Page title="Gold Exchange Report" subtitle="Branch exchange history · View only"><div className="gold-exchange"><header className="exchange-header"><div><small>GOLD EXCHANGE · REPORT / HISTORY</small><h2>Completed and pending exchanges</h2><p>Supervisory report only. Exchange creation, approval and settlement controls are unavailable.</p></div><span className="exchange-status">VIEW ONLY</span></header>{error?<ErrorState text={error} retry={load}/>:!data?<EmptyState text="Loading Gold Exchange history…"/>:<section className="completion-card"><small>BRANCH EXCHANGE HISTORY</small><div className="available-table mt-3"><header><span>EXCHANGE</span><span>DATE</span><span>CUSTOMER</span><span>AGREED VALUE</span><span>SETTLEMENT</span><span>STATUS</span></header>{data.items.map((row:any)=><article key={row.id}><span><b>{row.exchange_number}</b><small>{row.salesperson}</small></span><span>{new Date(row.created_at).toLocaleDateString('en-IN')}</span><span><b>{row.customer.name}</b><small>{row.customer.phone}</small></span><span>{formatMoney(row.agreed_exchange_value)}</span><span>{row.payment_direction?.replaceAll('_',' ')||'—'}<small>{formatMoney(row.settlement_amount)}</small></span><span><button className="secondary-action" onClick={()=>setSelected(row)}>{row.status} · View</button></span></article>)}{!data.items.length&&<p>No Gold Exchange records found in this branch.</p>}</div></section>}{selected&&<div className="payment-confirm-backdrop" role="dialog" aria-modal="true"><section className="max-w-[620px]"><small>GOLD EXCHANGE REPORT</small><h3>{selected.exchange_number}</h3><dl className="grid grid-cols-2 gap-3 text-left"><Fact label="Customer" value={selected.customer.name}/><Fact label="Sales Person / Actor" value={selected.salesperson}/><Fact label="Old gold" value={selected.old_gold.description}/><Fact label="Net gold" value={`${selected.old_gold.net_weight} g`}/><Fact label="Calculated value" value={formatMoney(selected.calculated_gold_value)}/><Fact label="Agreed value" value={formatMoney(selected.agreed_exchange_value)}/><Fact label="New jewellery total" value={formatMoney(selected.new_jewellery_total)}/><Fact label="Settlement" value={`${selected.payment_direction?.replaceAll('_',' ')||'BALANCED'} · ${formatMoney(selected.settlement_amount)}`}/><Fact label="Status" value={selected.status}/><Fact label="Branch" value={selected.branch}/></dl><div><button className="primary-action" onClick={()=>setSelected(undefined)}>Close</button></div></section></div>}</div></Page>;
}
function Fact({label,value}:{label:string;value:any}){return <div><dt className="text-[9px] text-[#82847f]">{label}</dt><dd className="m-0 font-bold">{value||'—'}</dd></div>}
