import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Filter, Gem, Search, X } from 'lucide-react';
import { api } from '../auth';
import { Page } from '../components/Page';
import { formatMoney } from '../utils/format';
import '../styles/returns-register.css';
import '../styles/returns-light.css';

const reasons=['CUSTOMER_CHANGED_MIND','SIZE_ISSUE','DESIGN_ISSUE','MANUFACTURING_DEFECT','QUALITY_ISSUE','DAMAGED_JEWELLERY','WRONG_JEWELLERY_SUPPLIED','HALLMARK_HUID_ISSUE','STONE_ISSUE','OTHER'];
const conditions=['GOOD','WORN','DAMAGED','BROKEN','MISSING_STONE','STONE_DAMAGE','SCRATCHED','TAMPERED','DEFECTIVE','REQUIRES_INSPECTION','SCRAP_MELT_CANDIDATE'];
const dispositions=['RETURN_TO_AVAILABLE_STOCK','QUALITY_INSPECTION','REPAIR','PENDING_ASSESSMENT','SCRAP_MELT','SUPPLIER_RETURN'];
const statuses=['REFUNDED','CREDITED','REQUESTED','UNDER_REVIEW','APPROVED','REJECTED','CLOSED','CANCELLED'];
const label=(value:string)=>value?.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())||'—';

export function ReturnsPage(){
  const[list,setList]=useState<any>({items:[],total_count:0,total_refund:'0',page:1,total_pages:1}),[loading,setLoading]=useState(true),[listError,setListError]=useState('');
  const[search,setSearch]=useState(''),[status,setStatus]=useState(''),[period,setPeriod]=useState('ALL'),[reasonFilter,setReasonFilter]=useState(''),[page,setPage]=useState(1),[filtersOpen,setFiltersOpen]=useState(false);
  const[invoice,setInvoice]=useState(''),[finding,setFinding]=useState(false),[findError,setFindError]=useState(''),[sale,setSale]=useState<any>(null),[detail,setDetail]=useState<any>(null);

  function dates(){const now=new Date(),iso=(d:Date)=>d.toISOString().slice(0,10);if(period==='TODAY')return{date_from:iso(now),date_to:iso(now)};if(period==='YESTERDAY'){const d=new Date(now);d.setDate(d.getDate()-1);return{date_from:iso(d),date_to:iso(d)}}if(period==='WEEK'){const d=new Date(now);d.setDate(d.getDate()-7);return{date_from:iso(d),date_to:iso(now)}}if(period==='MONTH')return{date_from:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,date_to:iso(now)};return{}}
  async function load(){setLoading(true);setListError('');try{setList((await api.get('/pos/returns',{params:{search:search||undefined,status:status||undefined,reason:reasonFilter||undefined,page,page_size:25,...dates()}})).data)}catch(e:any){setListError(e.response?.data?.error?.message||'Unable to load returns.')}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),400);return()=>clearTimeout(timer)},[search,status,period,reasonFilter,page]);
  async function findInvoice(){if(!invoice.trim())return;setFinding(true);setFindError('');try{const rows=(await api.get('/pos/returns/search',{params:{q:invoice.trim()}})).data;if(!rows.length)throw new Error('not-found');setSale(rows[0])}catch(e:any){setFindError(e.response?.data?.error?.message||'No eligible gold sale found for this invoice.')}finally{setFinding(false)}}
  function clearFilters(){setSearch('');setStatus('');setPeriod('ALL');setReasonFilter('');setPage(1);setFiltersOpen(false)}
  const active=Boolean(status||reasonFilter||period!=='ALL');
  return <Page title="Return & Reversal" subtitle="Gold jewellery sale returns and authoritative refunds">
    <div className="returns-layout"><section className="returns-register"><div className="register-summary"><div><small>RETURNS</small><strong>{list.total_count}</strong></div><div><small>TOTAL REFUND VALUE</small><strong>{formatMoney(list.total_refund)}</strong></div></div><div className="register-tools"><label><Search/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search return or invoice number..."/>{search&&<button onClick={()=>setSearch('')}><X/></button>}</label><button className={active?'filter active':'filter'} onClick={()=>setFiltersOpen(!filtersOpen)}><Filter/> Filter {active&&<i/>}</button>{filtersOpen&&<FilterPanel status={status} setStatus={setStatus} period={period} setPeriod={setPeriod} reason={reasonFilter} setReason={setReasonFilter} clear={clearFilters} close={()=>setFiltersOpen(false)}/>}</div>{active&&<div className="active-filters">{period!=='ALL'&&<span>{label(period)}</span>}{status&&<span>{label(status)}</span>}{reasonFilter&&<span>{label(reasonFilter)}</span>}<button onClick={clearFilters}>Clear filters</button></div>}
      <ReturnTable data={list.items} loading={loading} error={listError} search={search} retry={load} open={setDetail}/><div className="pagination"><span>{list.total_count?`Showing ${(page-1)*25+1}–${Math.min(page*25,list.total_count)} of ${list.total_count} returns`:'0 returns'}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft/></button><b>Page {page} of {list.total_pages}</b><button disabled={page>=list.total_pages} onClick={()=>setPage(page+1)}><ChevronRight/></button></div></div></section>
      <aside className="raise-return"><small>RAISE A RETURN</small><h2>Find original invoice</h2><p>Enter the invoice number for the previously sold gold jewellery.</p><label>Invoice number<input value={invoice} onChange={e=>setInvoice(e.target.value)} onKeyDown={e=>e.key==='Enter'&&findInvoice()} placeholder="INV-0000123"/></label>{findError&&<div className="raise-error">{findError}</div>}<button disabled={finding||!invoice.trim()} onClick={findInvoice}>{finding?'Finding invoice…':'Find'}</button><div className="workflow"><h3>Return workflow</h3><ol><li>Find original invoice</li><li>Select sold gold jewellery</li><li>Review condition and disposition</li><li>Preview authoritative refund</li><li>Refund and inventory update</li></ol></div></aside>
    </div>{sale&&<CreateReturn sale={sale} close={()=>setSale(null)} completed={()=>{setSale(null);setInvoice('');void load()}}/>}{detail&&<ReturnDrawer id={detail.id} initial={detail} close={()=>setDetail(null)}/>} 
  </Page>
}

function FilterPanel({status,setStatus,period,setPeriod,reason,setReason,clear,close}:any){return <div className="filter-popover"><div><b>FILTER RETURNS</b><button onClick={close}><X/></button></div><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Date<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="ALL">All dates</option><option value="TODAY">Today</option><option value="YESTERDAY">Yesterday</option><option value="WEEK">Last 7 days</option><option value="MONTH">This month</option></select></label><label>Return reason<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">All reasons</option>{reasons.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><footer><button onClick={clear}>Clear</button><button onClick={close}>Apply</button></footer></div>}
function ReturnTable({data,loading,error,search,retry,open}:any){if(loading)return <div className="register-state">Loading returns…</div>;if(error)return <div className="register-state error">{error}<button onClick={retry}>Retry</button></div>;if(!data.length)return <div className="register-state"><Gem/><b>No gold returns found.</b><span>{search?`No returns found for “${search}”.`:'Try another search or clear the filters.'}</span></div>;return <div className="returns-table"><header><span>RETURN</span><span>DATE</span><span>ITEMS</span><span>REFUND</span><span>STATUS</span></header>{data.map((x:any)=><button key={x.id} onClick={()=>open(x)}><span><b>{x.return_number}</b><small>{x.invoice_number}</small></span><span>{new Date(x.created_at).toLocaleDateString('en-IN')}</span><span>1</span><span>{formatMoney(x.refund_amount)}</span><mark>{x.status}</mark></button>)}</div>}

function CreateReturn({sale,close,completed}:{sale:any;close:()=>void;completed:()=>void}){const[reason,setReason]=useState(reasons[0]),[condition,setCondition]=useState(conditions[0]),[disposition,setDisposition]=useState(dispositions[0]),[method,setMethod]=useState('ORIGINAL_PAYMENT'),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');const body={invoice_id:sale.invoice.id,item_id:sale.item.id,reason,condition,disposition,refund_method:method};async function quote(){setBusy('Calculating refund…');try{setPreview((await api.post('/pos/returns/preview',body)).data)}catch(e:any){setError(e.response?.data?.error?.message||'Unable to preview return.')}finally{setBusy('')}}async function submit(){setBusy('Submitting return…');try{await api.post('/pos/returns',body);completed()}catch(e:any){setError(e.response?.data?.error?.message||'Return failed.')}finally{setBusy('')}}const item=sale.item;return <div className="return-modal"><div><button className="modal-close" onClick={close}><X/></button><small>CREATE RETURN · {sale.invoice.invoice_number}</small><h2>{item.name}</h2><div className="gold-facts"><span>TAG<b>{item.tag_number}</b></span><span>HUID<b>{item.huid||'Not recorded'}</b></span><span>PURITY<b>{item.purity} / {item.fineness}</b></span><span>GROSS<b>{item.gross_weight} g</b></span><span>STONE<b>{item.stone_weight} g</b></span><span>NET GOLD<b>{item.net_weight} g</b></span><span>FINE GOLD<b>{item.fine_weight} g</b></span></div><div className="assessment-grid"><label>Reason<select value={reason} onChange={e=>{setReason(e.target.value);setPreview(null)}}>{reasons.map(x=><option value={x}>{label(x)}</option>)}</select></label><label>Condition<select value={condition} onChange={e=>{setCondition(e.target.value);setPreview(null)}}>{conditions.map(x=><option value={x}>{label(x)}</option>)}</select></label><label>Disposition<select value={disposition} onChange={e=>{setDisposition(e.target.value);setPreview(null)}}>{dispositions.map(x=><option value={x}>{label(x)}</option>)}</select></label></div>{error&&<div className="raise-error">{error}</div>}{preview?<div className="preview-total"><span>Authoritative refund<b>{formatMoney(preview.refund.final_refund)}</b></span><label>Refund method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="ORIGINAL_PAYMENT">Original payment</option><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option><option>STORE_CREDIT</option></select></label><button disabled={!!busy} onClick={submit}>{busy||'Process return'}</button></div>:<button className="preview-button" disabled={!!busy} onClick={quote}>{busy||'Preview refund'}</button>}</div></div>}
function ReturnDrawer({id,initial,close}:{id:string;initial:any;close:()=>void}){const[data,setData]=useState(initial),[loading,setLoading]=useState(true);useEffect(()=>{api.get(`/pos/returns/${id}`).then(r=>setData(r.data)).finally(()=>setLoading(false))},[id]);const item=data.original_snapshot||{};return <div className="return-drawer-backdrop"><aside className="return-drawer"><button className="drawer-close" onClick={close}><X/></button>{loading?<p>Loading return details…</p>:<><small>GOLD SALE RETURN</small><h2>{data.return_number}</h2><mark>{data.status}</mark><section><h3>Original invoice</h3><dl><dt>Invoice</dt><dd>{data.invoice_number}</dd><dt>Created</dt><dd>{new Date(data.created_at).toLocaleString('en-IN')}</dd></dl></section><section><h3>Gold jewellery</h3><dl><dt>Tag</dt><dd>{item.tag_number}</dd><dt>Barcode</dt><dd>{item.barcode}</dd><dt>HUID</dt><dd>{item.huid||'Not recorded'}</dd><dt>Purity</dt><dd>{item.purity} / {item.fineness}</dd></dl><div className="drawer-weights"><span>Gross<b>{item.gross_weight} g</b></span><span>Stone<b>{item.stone_weight} g</b></span><span>Net<b>{item.net_weight} g</b></span><span>Fine<b>{item.fine_weight} g</b></span></div></section><section><h3>Return and refund</h3><dl><dt>Reason</dt><dd>{label(data.reason)}</dd><dt>Condition</dt><dd>{label(data.condition)}</dd><dt>Disposition</dt><dd>{label(data.disposition)}</dd><dt>Refund</dt><dd><b>{formatMoney(data.refund_amount)}</b></dd><dt>Method</dt><dd>{label(data.refund_method)}</dd></dl></section></>}</aside></div>}
