import { useEffect,useState } from 'react';
import { Search,UserPlus,X } from 'lucide-react';
import { api } from '../../auth';
import type { Customer } from '../../types/customer';
import '../../styles/customer-selector.css';

export function SelectedCustomerCard({customer,onOpen,onRemove}:{customer:Customer|null;onOpen:()=>void;onRemove:()=>void}){
  return <div className="customer-card"><small>CUSTOMER</small>{customer?<><h3>{customer.name}</h3><p>{customer.phone}</p><div><button onClick={onOpen}>Change</button><button onClick={()=>confirm('Remove customer from this bill?')&&onRemove()}>Remove</button></div></>:<><h3>No customer selected</h3><p>Attach a customer to this gold jewellery bill.</p><button className="add-customer" onClick={onOpen}><UserPlus/> Add customer</button></>}</div>
}

export function CustomerSelector({open,onClose,onSelect}:{open:boolean;onClose:()=>void;onSelect:(customer:Customer)=>void}){
  const[query,setQuery]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[creating,setCreating]=useState(false);
  async function search(){setLoading(true);setError('');try{setCustomers((await api.get('/pos/customers',{params:{search:query||undefined,page_size:20}})).data.items)}catch(e:any){setError(e.response?.data?.error?.message||'Unable to load customers.')}finally{setLoading(false)}}
  useEffect(()=>{if(open){const timer=setTimeout(()=>void search(),query?400:0);return()=>clearTimeout(timer)}},[open,query]);
  if(!open)return null;
  return <div className="customer-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section><button className="customer-close" onClick={onClose}><X/></button>{creating?<CustomerCreateForm initialPhone={/^\d{10}$/.test(query)?query:''} cancel={()=>setCreating(false)} saved={onSelect}/>:<><small>ADD CUSTOMER</small><h2>Select customer</h2><div className="customer-search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer by name or phone"/><button onClick={search}>Search</button></div>{loading?<div className="customer-state">Searching customers…</div>:error?<div className="customer-state error">{error}<button onClick={search}>Retry</button></div>:customers.length?<div className="customer-results"><p>{customers.length} customer{customers.length===1?'':'s'} found</p>{customers.map(customer=><button key={customer.id} onClick={()=>onSelect(customer)}><span><b>{customer.name}</b><small>{customer.phone}{customer.email?` · ${customer.email}`:''}</small></span><em>Select</em></button>)}</div>:<div className="customer-state"><b>No customer found</b><span>{query?`No customer matches “${query}”.`:'Create the first customer for this business.'}</span></div>}<button className="create-customer" onClick={()=>setCreating(true)}><UserPlus/> Create new customer</button></>}</section></div>
}

function CustomerCreateForm({initialPhone,cancel,saved}:{initialPhone:string;cancel:()=>void;saved:(customer:Customer)=>void}){
  const[form,setForm]=useState({name:'',phone:initialPhone,email:'',address:'',city:'',state:'',pin_code:'',gstin:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[duplicate,setDuplicate]=useState<Customer|null>(null);
  const set=(key:string,value:string)=>setForm({...form,[key]:value});
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(form.name.trim().length<2){setError('Customer name is required.');return}if(!/^[6-9]\d{9}$/.test(form.phone.replace(/\D/g,''))){setError('Enter a valid 10-digit Indian mobile number.');return}setBusy(true);try{const body=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v.trim()||null]));const{data}=await api.post('/pos/customers',body);saved(data)}catch(e:any){if(e.response?.status===409){const d=e.response.data?.error?.details;setDuplicate(d?{id:d.customer_id,name:d.name,phone:d.phone}:null);setError('Customer already exists.')}else setError(e.response?.data?.error?.message||'Unable to create customer.')}finally{setBusy(false)}}
  return <form className="customer-create" onSubmit={submit}><small>CREATE CUSTOMER</small><h2>New retail customer</h2><div className="customer-form-grid"><label>Name *<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Phone *<input required inputMode="numeric" maxLength={12} value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>City<input value={form.city} onChange={e=>set('city',e.target.value)}/></label><label className="wide">Address<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>State<input value={form.state} onChange={e=>set('state',e.target.value)}/></label><label>PIN code<input inputMode="numeric" maxLength={6} value={form.pin_code} onChange={e=>set('pin_code',e.target.value)}/></label><label>GSTIN<input maxLength={15} value={form.gstin} onChange={e=>set('gstin',e.target.value)}/></label></div>{error&&<div className="customer-form-error">{error}</div>}{duplicate&&<button type="button" className="select-existing" onClick={()=>saved(duplicate)}>Select existing customer: {duplicate.name}</button>}<footer><button type="button" onClick={cancel}>Cancel</button><button disabled={busy}>{busy?'Creating customer…':'Save customer'}</button></footer></form>
}
