import { Gem } from 'lucide-react';
import type { JewelleryItem, PosUser, PriceQuote } from '../../types';
import { formatMoney } from '../../utils/format';

type CartItem = JewelleryItem & { product_id?: string; name?: string; wastage_percent?: string | null };
export interface EstimatedBillData { estimateNumber: string; issuedAt: Date; customer: { name?: string; phone?: string; email?: string | null } | null; salesperson: string; branch: string; items: Array<{ id: string; name: string; purity: string; quantity: number; grossWeight: number; stoneWeight: number; netWeight: number; fineGold: number; wastage: string; goldRate: number; makingCharges: number; gst: number; total: number }>; weights: { totalItems: number; totalQuantity: number; gross: number; net: number; fine: number }; pricing: { goldValue: number; wastage: number; makingCharges: number; stoneCharges: number; discount: number; taxableValue: number; gst: number; total: number } }
const number = (value: unknown) => Number(value || 0);

/** The sole data model consumed by the shared document in every output medium. */
export function createEstimatedBillData({ cart, quotes, customer, user, issuedAt = new Date() }: { cart: JewelleryItem[]; quotes: Record<string, PriceQuote>; customer: EstimatedBillData['customer']; user: PosUser; issuedAt?: Date }): EstimatedBillData {
  const groups = Object.values((cart as CartItem[]).reduce((all, item) => { const key = item.product_id || item.id; (all[key] ||= []).push(item); return all; }, {} as Record<string, CartItem[]>));
  const sum = (items: CartItem[], field: keyof JewelleryItem) => items.reduce((total, item) => total + number(item[field]), 0);
  const amount = (items: CartItem[], field: keyof PriceQuote['breakdown']) => items.reduce((total, item) => total + number(quotes[item.id]?.breakdown[field]), 0);
  const all = cart as CartItem[];
  const items = groups.map(group => { const first = group[0]; return { id: first.product_id || first.id, name: first.name || first.sku || 'Gold jewellery', purity: first.purity || '—', quantity: group.length, grossWeight: sum(group, 'gross_weight'), stoneWeight: sum(group, 'stone_weight'), netWeight: sum(group, 'net_weight'), fineGold: sum(group, 'fine_weight'), wastage: first.wastage_percent ?? 'Not configured', goldRate: number(quotes[first.id]?.rate_per_gram), makingCharges: amount(group, 'making_charge'), gst: amount(group, 'tax_amount'), total: amount(group, 'total') }; });
  const pricing = { goldValue: amount(all, 'metal_value'), wastage: amount(all, 'wastage_value'), makingCharges: amount(all, 'making_charge'), stoneCharges: 0, discount: amount(all, 'discount'), taxableValue: amount(all, 'subtotal'), gst: amount(all, 'tax_amount'), total: amount(all, 'total') };
  return { estimateNumber: `EST-${issuedAt.getTime().toString(36).toUpperCase()}`, issuedAt, customer, salesperson: user.full_name, branch: user.branch_name || '—', items, weights: { totalItems: items.length, totalQuantity: all.length, gross: sum(all, 'gross_weight'), net: sum(all, 'net_weight'), fine: sum(all, 'fine_weight') }, pricing };
}

export function EstimatedBillDocument({ data }: { data: EstimatedBillData }) {
  const priceRows: Array<[string, number, boolean?]> = [['Gold value', data.pricing.goldValue], ['Wastage', data.pricing.wastage], ['Making charges', data.pricing.makingCharges], ['Stone charges', data.pricing.stoneCharges], ['Discount', data.pricing.discount, true], ['Taxable value', data.pricing.taxableValue], ['GST', data.pricing.gst]];
  return <article className="estimate-print-document" data-estimate-id={data.estimateNumber}>
    <header className="quotation-hero"><span className="quotation-gem"><Gem /></span><small>POS GOLD · JEWELLERY COUNTER</small><h1>Price Estimate</h1><p>Provisional jewellery quotation</p><div><b>ESTIMATE / QUOTATION</b><strong>{data.estimateNumber}</strong><em>NOT A TAX INVOICE</em></div></header>
    <section className="quotation-customer"><div><small>{data.customer ? 'CUSTOMER' : 'WALK-IN CUSTOMER'}</small><h2>{data.customer?.name || 'Walk-in Customer'}</h2><p>{data.customer?.phone || 'Phone —'}{data.customer?.email ? ` · ${data.customer.email}` : ''}</p></div><dl><div><dt>Estimate date</dt><dd>{data.issuedAt.toLocaleDateString('en-IN', { dateStyle: 'medium' })}</dd></div><div><dt>Time</dt><dd>{data.issuedAt.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</dd></div><div><dt>Sales person</dt><dd>{data.salesperson}</dd></div><div><dt>Branch</dt><dd>{data.branch}</dd></div></dl></section>
    <section className="quotation-items"><header><small>ITEM DETAILS</small><h2>Your selected jewellery</h2><span>{data.weights.totalItems} design{data.weights.totalItems === 1 ? '' : 's'} · {data.weights.totalQuantity} piece{data.weights.totalQuantity === 1 ? '' : 's'}</span></header>{data.items.map((item, index) => <article className="quotation-item" key={item.id}><header><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{item.name}</h3><p>{item.purity} · Quantity <b>{item.quantity}</b></p></div><strong>{formatMoney(item.total)}<small>Estimated amount</small></strong></header><div className="quotation-facts"><Fact label="Gross weight" value={`${item.grossWeight.toFixed(3)} g`} /><Fact label="Stone weight" value={`${item.stoneWeight.toFixed(3)} g`} /><Fact label="Net weight" value={`${item.netWeight.toFixed(3)} g`} /><Fact label="Fine gold" value={`${item.fineGold.toFixed(3)} g`} /><Fact label="Wastage" value={item.wastage === 'Not configured' ? item.wastage : `${item.wastage}%`} /><Fact label="Gold rate" value={item.goldRate ? `${formatMoney(item.goldRate)} / g` : '—'} /><Fact label="Making charges" value={formatMoney(item.makingCharges)} /><Fact label="GST" value={formatMoney(item.gst)} /></div></article>)}</section>
    <section className="quotation-bottom"><div className="quotation-weight-summary"><small>WEIGHT SUMMARY</small><h2>Jewellery at a glance</h2><Fact label="Total items" value={data.weights.totalItems} /><Fact label="Total quantity" value={data.weights.totalQuantity} /><Fact label="Total gross weight" value={`${data.weights.gross.toFixed(3)} g`} /><Fact label="Total net weight" value={`${data.weights.net.toFixed(3)} g`} /><Fact label="Total fine gold" value={`${data.weights.fine.toFixed(3)} g`} /></div><div className="quotation-price-summary"><small>PRICE BREAKDOWN</small>{priceRows.map(([label, value, negative]) => <p key={label}><span>{label}</span><b>{negative ? '− ' : ''}{formatMoney(value)}</b></p>)}<p className="quotation-grand"><span>Estimated total</span><b>{formatMoney(data.pricing.total)}</b></p></div></section>
    <footer className="quotation-note"><small>IMPORTANT NOTICE</small><p>This is a provisional price estimate and not a tax invoice. Final pricing, gold rate, wastage, making charges, taxes, availability and other applicable charges will be confirmed at final billing/checkout.</p></footer>
  </article>;
}
function Fact({ label, value }: { label: string; value: string | number }) { return <p><span>{label}</span><b>{value}</b></p>; }
